blank_issues_enabled: true
contact_links:
  - name: "\U0001F4AC 질문 & 토론"
    url: https://github.com/seunggulee1007/tistory-monologuje-skin/discussions
    about: 버그나 기능 제안이 아닌 일반적인 질문은 Discussions를 이용해 주세요.
